name: Create Release Schemas

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "ESPHome release tag"
        required: true
        type: string

jobs:
  update-schemas:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout esphome-schema repo
        uses: actions/checkout@v4
        with:
          ref: release
          persist-credentials: true # important for push

      - name: Set up Python 3.9
        id: python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: 3.9

      - name: Clone ESPHome repository
        run: |
          git clone --depth=1 --branch=${{ inputs.tag }} https://github.com/esphome/esphome.git

      - name: Install ESPHome dependencies
        run: |
          cd esphome
          pip install -r requirements.txt -r requirements_test.txt
          pip install -e .

      - name: Generate language schema
        run: |
          python esphome/script/build_language_schema.py --output-path=./schema

      - name: Clone ESPHome docs repository
        run: |
          git clone --depth=1 --branch=${{ inputs.tag }} https://github.com/esphome/esphome-docs.git

      - name: Install ESPHome docs dependencies
        run: |
          cd esphome-docs
          pip install -r requirements.txt

      - name: Add docs to language schema
        run: |
          cd esphome-docs
          python -m sphinx -a -Dextensions=github,seo,sitemap,schema_doc . _build

      - name: Commit changes to schema folder
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add schema
          git diff --cached --quiet || git commit -m "Release ${{ inputs.tag }}"
          git push
          git tag ${{ inputs.tag }}
          git push --tags
